"""empty message

Revision ID: 3e22a4964f06
Revises: f6270d8e4a5b
Create Date: 2026-02-01 21:20:56.283159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e22a4964f06'
down_revision = 'f6270d8e4a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_favorites',
    sa.Column('Character_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('Character_id', 'User_id')
    )
    op.create_table('location_favorites',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('location_id', 'User_id')
    )
    op.drop_table('favorites_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_table',
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('User_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Character_id'], ['character.id'], name='favorites_table_Character_id_fkey'),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], name='favorites_table_User_id_fkey'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='favorites_table_location_id_fkey')
    )
    op.drop_table('location_favorites')
    op.drop_table('character_favorites')
    # ### end Alembic commands ###
