"""empty message

Revision ID: b430281eed10
Revises: a5cffa318ac2
Create Date: 2026-01-29 21:56:22.802660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b430281eed10'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote', sa.String(length=180), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('use', sa.String(length=180), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=False),
    sa.Column('town', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('favorites_table',
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('Character_id', sa.Integer(), nullable=True),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], )
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    op.drop_table('favorites_table')
    op.drop_table('location')
    op.drop_table('character')
    # ### end Alembic commands ###
