"""empty message

Revision ID: f6270d8e4a5b
Revises: b430281eed10
Create Date: 2026-01-29 21:57:37.694096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6270d8e4a5b'
down_revision = 'b430281eed10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_table', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('Character_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('User_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_table', schema=None) as batch_op:
        batch_op.alter_column('User_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('Character_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
